channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - pip
  - pytorch=1.3.1 
  - torchvision
  - tensorflow-gpu=1.14
  - pip:
    - stable-baselines=2.10.2
    - gym=0.15.7

