"""
Pydantic models for code generation (Agent 2 output).
"""

from typing import Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class CodeHunk(BaseModel):
    """Structured unified-diff hunk for review/approval."""

    id: str = Field(description="Stable hunk id (e.g. hunk-1)")
    old_start: int = Field(description="Original code start line (1-based)")
    old_count: int = Field(description="Original code line count in hunk")
    new_start: int = Field(description="Patched code start line (1-based)")
    new_count: int = Field(description="Patched code line count in hunk")
    header: str = Field(default="", description="Optional hunk header context")
    lines: List[str] = Field(
        default_factory=list,
        description="Unified diff body lines with + / - / context prefixes",
    )
    status: Literal["pending", "approved", "rejected"] = Field(
        default="pending",
        description="Review status for this hunk",
    )


class CodeArtifact(BaseModel):
    """Artifact payload for Studio diff/hunk visualization."""

    file_name: str = Field(default="simulation.py")
    base_code: str = Field(default="", description="Pre-patch code text")
    full_code: str = Field(
        default="",
        description="Complete file content (for initial generation or patched result)",
    )
    patch: str = Field(default="", description="Unified diff patch text")
    hunks: List[CodeHunk] = Field(default_factory=list)
    metadata: Dict[str, str] = Field(default_factory=dict)


class GeneratedCode(BaseModel):
    """
    Represents the code generated by the Code Generation Agent (Agent 2).

    Attributes:
        code: The complete Python code for the simulation
        imports: List of import statements used
        api_version: PyChrono API version targeted
        validation_status: Current validation state
        compilation_errors: List of compilation errors if any
        retry_count: Number of retry attempts made
    """

    file_name: str = Field(
        default="simulation.py",
        description="Canonical file name for the generated simulation source"
    )

    code: str = Field(
        description="Complete PyChrono simulation code"
    )

    imports: List[str] = Field(
        default_factory=list,
        description="Python imports used in the code"
    )

    api_version: str = Field(
        default="unknown",
        description="Target PyChrono API version"
    )

    validation_status: Literal[
        "not_validated",
        "syntax_valid",
        "compile_valid",
        "validation_failed"
    ] = Field(
        default="not_validated",
        description="Validation status of the generated code"
    )

    compilation_errors: List[str] = Field(
        default_factory=list,
        description="Compilation errors encountered"
    )

    retry_count: int = Field(
        default=0,
        description="Number of retry attempts"
    )

    base_code: Optional[str] = Field(
        default=None,
        description="Original code before patch application (fix mode)",
    )

    patch: Optional[str] = Field(
        default=None,
        description="Unified diff patch text describing incremental changes",
    )

    hunks: List[CodeHunk] = Field(
        default_factory=list,
        description="Parsed patch hunks for hunk-level review",
    )

    applied_code: Optional[str] = Field(
        default=None,
        description="Code produced by applying patch to base_code",
    )

    patch_apply_status: Literal["not_attempted", "applied", "failed"] = Field(
        default="not_attempted",
        description="Patch application outcome",
    )

    patch_apply_error: Optional[str] = Field(
        default=None,
        description="Error message when patch application fails",
    )

    class Config:
        json_schema_extra = {
            "example": {
                "code": "import pychrono.core as chrono\\n\\nsystem = chrono.ChSystemNSC()\\n...",
                "imports": ["pychrono", "numpy", "matplotlib"],
                "api_version": "10.0.0",
                "validation_status": "compile_valid",
                "compilation_errors": [],
                "retry_count": 0,
                "base_code": "import pychrono.core as chrono\\n...",
                "patch": "@@ -1,1 +1,2 @@\\n import pychrono.core as chrono\\n+import numpy as np",
                "hunks": [],
                "applied_code": "import pychrono.core as chrono\\nimport numpy as np\\n...",
                "patch_apply_status": "applied",
                "patch_apply_error": None,
            }
        }


class CompilationError(BaseModel):
    """
    Represents a single compilation error.

    Attributes:
        error_type: Type of error (syntax, import, runtime, etc.)
        message: Error message
        line_number: Line number where error occurred (if available)
        suggestion: Potential fix suggestion
    """

    error_type: Literal["syntax", "import", "runtime", "type", "other"] = Field(
        description="Type of compilation error"
    )

    message: str = Field(
        description="Error message from the compiler"
    )

    line_number: Optional[int] = Field(
        default=None,
        description="Line number where the error occurred"
    )

    suggestion: Optional[str] = Field(
        default=None,
        description="Suggested fix for the error"
    )
